apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-overlay
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/car-overlay.git
    targetRevision: HEAD
    path: deploy
    helm:
      valuesObject:
        ingress:
          host: pdv-auto.loicgombeaud.com
  destination:
    server: https://kubernetes.default.svc
    namespace: car-overlay
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
