apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radars
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/radars.git
    targetRevision: HEAD
    path: deploy
    helm:
      valuesObject:
        ingress:
          host: radars.velo-cite.org
  destination:
    server: https://kubernetes.default.svc
    namespace: radars
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
