apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compteurs-velo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/compteurs-velo.git
    targetRevision: feat/deploy
    path: deploy
    helm:
      valuesObject:
        ingress:
          host: compteurs-velo.loicgombeaud.com
  destination:
    server: https://kubernetes.default.svc
    namespace: compteurs-velo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
