apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coursdetoulouse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/ruedetoulouse.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: coursdetoulouse
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
