apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employer-dataviz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/employer_dataviz.git
    targetRevision: feat/deploy
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: employer-dataviz
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
