apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liberons-la-rue
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/liberons-la-rue.git
    targetRevision: feat/deploy
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: liberons-la-rue
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
