apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openrouteservice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/openrouteservice-helm
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: openrouteservice
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
