apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parking-bordeaux-metropole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/parking-bordeaux-metropole.git
    targetRevision: HEAD
    path: deploy
    helm:
      valuesObject:
        ingress:
          host: parking.loicgombeaud.com
  destination:
    server: https://kubernetes.default.svc
    namespace: parking-bordeaux-metropole
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
