apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plan-de-circulation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/plan-de-circulation.git
    targetRevision: feat/deploy
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: plan-de-circulation
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
