apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radars
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/radars.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: radars
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
