apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voiesbordelaises
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LoicGombeaud/voiesbordelaises.git
    targetRevision: feat/deploy
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: voiesbordelaises
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
