apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.keel.sh
    targetRevision: 1.0.2
    chart: keel
    helm:
      valuesObject:
        service:
          enabled: true
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: basic-auth
          hosts:
            - host: keel.loicgombeaud.com
              paths:
                - /
          tls:
            - hosts:
              - keel.loicgombeaud.com
              secretName: keel-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: keel
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
